# This file is defining a service where when the requester queries the service, the service returns a path to the next frontier node

# request  goes on this sie of the --- (response on the other side)

string requester_name
uint64 requester_id 
---
bool success
string message
